cookie:
  expiry_days: 7
  key: invoice_extractor_secret_2026
  name: invoice_extractor_auth
credentials:
  usernames:
    gil@greenseo.co.il:
      email: gil@greenseo.co.il
      name: Gil User
      password: $2b$12$T2G5SN.9sVbpUxFovIiACOYNUk0bSFk4Z/Zz2sfdcoX/F2ubdbN0C
      role: user
    gil@zed66.com:
      email: gil@zed66.com
      name: Gil Admin
      password: $2b$12$IvIIEFFytxyg.IpbD6KoDuLkNNhuJwGmMIc4PIVabTxHmQ8kGV8X2
      role: admin
    moshe:
      email: 'moshe@cohen-cpa.co.il '
      name: Moshe Cohen
      password: $2b$12$3l.7cY3xfq3tFihow5bbTO/WJGGyFrUgTnRdXV6p6Bi0.hu0FE2KG
      role: user
pre-authorized:
  emails: []
